workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
      android: true
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FCI_BUILD_DIR/build
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
